spring:
  profiles:
    active: development
  datasource:
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  batch:
    job:
      enabled: false

---
spring:
  profiles: development
  datasource:
    initialize: false
    url: jdbc:h2:tcp://localhost/~/test;MVCC=TRUE;AUTO_RECONNECT=TRUE;IFEXISTS=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: sa

logging:
  file: /var/log/PracticeSpringBatchLog/PracticeSpringBatch.log
  level:
    root: INFO
    org.springframework.web: INFO

---
spring:
  profiles: integration
  datasource:
    initialize: false
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa

logging:
  file: logs/PracticeSpringBatch.log
  level:
    root: INFO
    org.springframework.web: INFO

---
spring:
  profiles: production
  datasource:
    initialize: false
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa

logging:
  file: logs/PracticeSpringBatch.log
  level:
    root: INFO
    org.springframework.web: INFO
